/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.AreaConcurso;
import classes.Concurso;
import classes.Fase;
import fachada.Fachada;
import fachada.IFachada;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAFAELSANTIAGO
 */
public class CalcularNotasConcursandos extends javax.swing.JFrame {

    /**
     * Creates new form CalcularNotasConcursandos
     */
    List<AreaConcurso> areas;
    List<Concurso> concursos;
    List<Fase> fases;
    IFachada fachada = Fachada.obterInstancia();
    
    public CalcularNotasConcursandos() {
        initComponents();
        try {
            concursos = new ArrayList<Concurso>();
            concursos = fachada.consultarTodosConcurso();            
            this.carregarListaConcursos();            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    
    public void carregarComboAreasConcurso() {
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel();
        for (AreaConcurso areaConcurso : areas) {
            comboModel.addElement(areaConcurso.getNome());
        }
        ComboAreasConcurso.setModel(comboModel);
    }
    
    public void carregarComboFases() {
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel();
        fases = areas.get(ComboAreasConcurso.getSelectedIndex()).getFases();
        for (int i = 0; i < fases.size(); i++) {
            comboModel.addElement((i + 1) + "ª Fase");
        }        
        ComboFasesAreaConcurso.setModel(comboModel);
    }
    
    public void carregarListaConcursos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Nome do Concurso", "Empresa Patrocinadora", "Data das Inscrições", "Data do Encerramento"});
        for (Concurso concurso : concursos) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            modelo.addRow(new Object[]{concurso.getNomeConcurso(), concurso.getEmpresa().getNome(), sdf.format(concurso.getDatainscricao().getTime()), sdf.format(concurso.getDatafinal().getTime())});
        }
        TableConcursos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboAreasConcurso = new javax.swing.JComboBox();
        ComboFasesAreaConcurso = new javax.swing.JComboBox();
        ButtonCadastrarCartResp = new javax.swing.JButton();
        ButtonIniciarCorrecao = new javax.swing.JButton();
        ButtonVisualizarResultado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableConcursos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ComboAreasConcurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboAreasConcursoMouseClicked(evt);
            }
        });

        ButtonCadastrarCartResp.setText("Cadastrar Cartoes Resposta");
        ButtonCadastrarCartResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarCartRespActionPerformed(evt);
            }
        });

        ButtonIniciarCorrecao.setText("Iniciar Correção");
        ButtonIniciarCorrecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIniciarCorrecaoActionPerformed(evt);
            }
        });

        ButtonVisualizarResultado.setText("Visualizar Resultado");
        ButtonVisualizarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVisualizarResultadoActionPerformed(evt);
            }
        });

        TableConcursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableConcursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableConcursos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ButtonCadastrarCartResp, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(ButtonIniciarCorrecao)
                        .addGap(26, 26, 26)
                        .addComponent(ButtonVisualizarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboAreasConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(ComboFasesAreaConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboAreasConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboFasesAreaConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadastrarCartResp)
                    .addComponent(ButtonIniciarCorrecao)
                    .addComponent(ButtonVisualizarResultado))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboAreasConcursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboAreasConcursoMouseClicked
        // TODO add your handling code here:
        this.carregarComboFases();
    }//GEN-LAST:event_ComboAreasConcursoMouseClicked
    
    private void ButtonCadastrarCartRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarCartRespActionPerformed
        // TODO add your handling code here:
        ListarConcursandosFase lcf = new ListarConcursandosFase(fases.get(ComboFasesAreaConcurso.getSelectedIndex()));
        lcf.setVisible(true);
    }//GEN-LAST:event_ButtonCadastrarCartRespActionPerformed
    
    private void TableConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableConcursosMouseClicked
        // TODO add your handling code here:
        if (TableConcursos.getSelectedRow() != -1) {
            areas = concursos.get(TableConcursos.getSelectedRow()).getAreasConcurso();
            carregarComboAreasConcurso();
            carregarComboFases();
        }
    }//GEN-LAST:event_TableConcursosMouseClicked

    private void ButtonIniciarCorrecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIniciarCorrecaoActionPerformed
        // TODO add your handling code here:
        CorrecaoProvasFase cpf = new CorrecaoProvasFase(fases.get(ComboFasesAreaConcurso.getSelectedIndex()));
        cpf.setVisible(true);
    }//GEN-LAST:event_ButtonIniciarCorrecaoActionPerformed

    private void ButtonVisualizarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVisualizarResultadoActionPerformed
        // TODO add your handling code here:
        ListaClassificacao lcl = new ListaClassificacao(fases.get(ComboFasesAreaConcurso.getSelectedIndex()));
        lcl.setVisible(true);
    }//GEN-LAST:event_ButtonVisualizarResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcularNotasConcursandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcularNotasConcursandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcularNotasConcursandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcularNotasConcursandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcularNotasConcursandos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrarCartResp;
    private javax.swing.JButton ButtonIniciarCorrecao;
    private javax.swing.JButton ButtonVisualizarResultado;
    private javax.swing.JComboBox ComboAreasConcurso;
    private javax.swing.JComboBox ComboFasesAreaConcurso;
    private javax.swing.JTable TableConcursos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
